import Head from "next/head";
import Image from "next/image";
import Card1 from "../components/Card1.js";
import Card2 from "../components/Card2.js";
import OwnedItem from "../components/OwnedItem.js";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.left}>
        <div className={styles.top}>
          <div className={styles.user_info}>
            <Image src={require("../assets/user.png")} width={70} />
            <span>LVL 2</span>
          </div>
          <div className={styles.top_info}>
            <h1>dingaling.eth</h1>
            <span>0xadgf....jkld</span>
          </div>
        </div>

        <div className={styles.links}>
          <div className={styles.link}>
            <Image src={require("../assets/twitter.png")} width={30} />
            <span>@dingalingts</span>
          </div>
          <div className={styles.link}>
            <Image src={require("../assets/globe.png")} width={25} />
          </div>
        </div>

        <p>
          An Investor / Collector of #NFTs and OG enthusiast. Co-Founder and
          owner of 📦 @nftboxes
        </p>

        <div className={styles.communities}>
          <span>Common communties (3)</span>
          <div className={styles.communities_images}>
            <Image src={require("../assets/main_1.png")} width={60} />
            <Image src={require("../assets/main_2.png")} width={60} />
            <Image src={require("../assets/main_3.png")} width={60} />
            <Image src={require("../assets/main_4.png")} width={60} />
          </div>
        </div>

        <div className={styles.owned}>
          <OwnedItem type="Art" quantity="12" />
          <OwnedItem type="Utility" quantity="12" />
          <OwnedItem type="PFP" quantity="12" />
          <OwnedItem type="Metaverse" quantity="12" />
          <OwnedItem type="Gaming" quantity="12" />
          <OwnedItem type="PFP" quantity="12" />
          <OwnedItem type="ens" quantity="12" />
        </div>

        <button>Subscribe</button>
      </div>

      <div className={styles.right}>
        <h1 className={styles.heading}>Highlights</h1>
        <div className={styles.right_top}>
          <Card1
            imagelink={require("../assets/card1.png")}
            title="ENS Linked"
            subtitle="ENS Linked"
            name="dingaling.eth"
            value="1.82"
            time="2 months ago"
            points="200"
            color="#4BDFFF"
          />

          <Card1
            imagelink={require("../assets/card2.png")}
            title="Best Flip"
            subtitle="Sold"
            name="CryptoPunk #2131"
            value="98.5"
            time="10 days ago"
            points="150"
            color="#FFC148"
          />

          <Card1
            imagelink={require("../assets/card3.png")}
            title="Should have..."
            subtitle="Mint"
            name="Rare Apepe #6974"
            value="98.5"
            time="10 days ago"
            points="200"
            color="#44FFC8"
          />

          <Card1
            imagelink={require("../assets/card4.png")}
            title="First NFT bought"
            subtitle="Bought"
            name="BAYC #7925"
            value="98.5"
            time="10 days ago"
            points="10"
            color="#4BDFFF"
          />

          {/* <Card1
            imagelink={require("../assets/card5.png")}
            title="Paper Handed"
            subtitle="Sold"
            name="Moonbird #7866"
            value="98.5"
            time="10 days ago"
            points="200"
            color="#44FFC8"
          /> */}
        </div>
        <div className={styles.right_bottom}>
          <Card2
            imageLink={require("../assets/card2_1.png")}
            time="3 Months"
            name="Azuki #9839"
            quantity="02.82"
            price="12.74"
            gain="21.6"
          />

          <Card2
            imageLink={require("../assets/card2_2.png")}
            time="3 Months"
            name="MAYC #9839"
            quantity="02.82"
            price="12.74"
            gain="21.6"
          />

          <Card2
            imageLink={require("../assets/card2_3.png")}
            time="3 Months"
            name="MoonBirds #9839"
            quantity="02.82"
            price="12.74"
            gain="21.6"
          />

          {/* <Card2
            imageLink={require("../assets/card2_4.png")}
            time="3 Months"
            name="Otherdeed #9839"
            quantity="02.82"
            price="12.74"
            gain="21.6"
          /> */}

          <Card2
            imageLink={require("../assets/card2_5.png")}
            time="3 Months"
            name="Cryptoz #9839"
            quantity="02.82"
            price="12.74"
            gain="21.6"
          />
        </div>
      </div>
    </div>
  );
}
